// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAc6Pv3LQHthwtHpfEWRnzvdzoxGHC4iM',
    appId: '1:694109088541:web:a820d2ab6885413093cff4',
    messagingSenderId: '694109088541',
    projectId: 'nulinz-d416d',
    authDomain: 'nulinz-d416d.firebaseapp.com',
    storageBucket: 'nulinz-d416d.firebasestorage.app',
    measurementId: 'G-HQCL689RKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPqsa_0x2EzBnTZzisTDjJnWmauILB44',
    appId: '1:694109088541:android:00522af231b308ea93cff4',
    messagingSenderId: '694109088541',
    projectId: 'nulinz-d416d',
    storageBucket: 'nulinz-d416d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgDSw9XKD003CtHVFltwzTcAfT-JNhXVw',
    appId: '1:694109088541:ios:be516af8a2d5fdba93cff4',
    messagingSenderId: '694109088541',
    projectId: 'nulinz-d416d',
    storageBucket: 'nulinz-d416d.firebasestorage.app',
    iosBundleId: 'com.example.nuLinz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgDSw9XKD003CtHVFltwzTcAfT-JNhXVw',
    appId: '1:694109088541:ios:be516af8a2d5fdba93cff4',
    messagingSenderId: '694109088541',
    projectId: 'nulinz-d416d',
    storageBucket: 'nulinz-d416d.firebasestorage.app',
    iosBundleId: 'com.example.nuLinz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAc6Pv3LQHthwtHpfEWRnzvdzoxGHC4iM',
    appId: '1:694109088541:web:066b0f649a0d6e4793cff4',
    messagingSenderId: '694109088541',
    projectId: 'nulinz-d416d',
    authDomain: 'nulinz-d416d.firebaseapp.com',
    storageBucket: 'nulinz-d416d.firebasestorage.app',
    measurementId: 'G-JYXG5GXPZS',
  );
}
